name: main

on:
  push:
    branches:
      - main

jobs:

  build:
    name: Build Docker images
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main

      - name: Show repository structure before build
        run: |
          echo "Current Directory: $(pwd)"
          echo "Listing files recursively before build:"
          ls -R

      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v2

      
      - name: Build backend
        id: build-backend
        uses: docker/build-push-action@v3
        with:
          file: ./Dockerfile
          push: false
          tags: tynvek1234/kurs-web1:latest

     

      - name: Save backend artifact
        uses: actions/upload-artifact@v3  
        with:
          name: backend-image
          path: ./
  tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Tests
        run: echo "Tests completed. Check the logs for results."
  push:
    name: Push Docker images to Docker Hub
    needs: tests 
    runs-on: ubuntu-latest

    steps:

      - name: Download backend artifact
        uses: actions/download-artifact@v3 
        with:
          name: backend-image
          path: ./

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push backend
        uses: docker/build-push-action@v3
        with:
          file: ./Dockerfile
          push: true
          tags: tynvek1234/kurs-web1:latest
